name: bookia
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  html: ^0.15.0
  gap: ^3.0.1
  dio: ^5.9.0
  confetti: ^0.8.0
  shared_preferences: ^2.5.3
  pinput: ^5.0.2
  go_router: ^16.2.4
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/book.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
          weight: 400
          style: normal
